name: temp_mobile
description: "Une application moderne de gestion de santé mentale pour prévenir le burnout."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0-59.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  
  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  
  # Navigation
  go_router: ^14.2.7
  
  # Local Storage
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Charts & Visualizations
  fl_chart: ^0.69.0
  
  # Animations
  rive: ^0.13.13
  lottie: ^3.1.2
  flutter_animate: ^4.5.0
  
  # Date & Time
  intl: ^0.20.2
  
  # Networking (for future features)
  dio: ^5.7.0
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  
  # Health & Sensors
  sensors_plus: ^6.0.1
  
  # Utils
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
